name: nim_conversationkit_ui
description: Conversation UI base on ConversationKit.
version: 1.2.0
homepage: https://github.com/netease-kit/nim-uikit-flutter

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

# Remove this line if you wish to publish to pub.dev
#publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  netease_common_ui:
    ">=1.2.0 <1.3.0"
#    path: ../../common/netease_common_ui
  nim_conversationkit:
    ">=1.2.0 <1.3.0"
#    path: ../nim_conversationkit
  netease_corekit_im:
    ">=1.2.0 <1.3.0"
#    path: ../../netease_corekit/netease_corekit_im
  netease_corekit:
    ">=1.2.0 <1.3.0"
#    path: ../../netease_corekit/netease_corekit
  nim_core: ^1.7.3
#    path: ../../nim_core/nim_core
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  provider: ^6.0.0
  yunxin_alog: ^2.0.0
  connectivity_plus: ^5.0.0
  flutter_slidable: ^3.0.0
  path_provider: ^2.0.11
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
